version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:13.0.1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn clean test
#      - run:
#          name: Save test results
#          command: |
#            mkdir -p ~/test-results/junit/
#            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
#          when: always
#      - store_test_results:
#          path: ~/test-results
#      - store_artifacts:
#          path: ~/test-results/junit